### PR TITLE
Use try! macro where appropriate instead of matching Result

### PR DESCRIPTION
**Pull request by mthjones**
Also use if let in a couple places

Most (all?) of the `map_err` calls should go away when custom errors are introduced by implementing `Into`/`From`.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Looks good, will merge on green from Travis.

**Comment by BenTheElder** [comment]
I have an Error enum in the works locally that should come out later that should fit in nicely with this.

That will leave implementing the rest of the bots api and switching to serde once I can derive it and alias the proper fields with serde_macros on stable, both of which should be pretty trivial.

**Comment by mthjones** [comment]
Nice! I'm looking forward to being able to use more of the Slack API. If any of the API's not spoken for, I can take a look at implementing it. The `im` stuff in particular would be useful for my [project][1] and [library][2].

[1]: https://github.com/mthjones/foosbot
[2]: https://github.com/mthjones/slackbot

**Comment by BenTheElder** [comment]
None of them are spoken for, I plan to expose those three and add the error
enum right now, and as far as I know no one else is actively working on
this so.

**Comment by BenTheElder** [comment]
The new error type is up in master, though I haven't published to cargo yet as I want to expose those api methods and review it a bit first, but 0.9.1 is on the way soon after I take care of that.

**Pull request merged**
