### PR TITLE
Move example into examples directory

### PR DESCRIPTION
**Pull request by mthjones**
To align with [cargo documentation][1].

[1]: http://doc.crates.io/guide.html#project-layout

### CODE REVIEW

**Comment by BenTheElder** [comment]
This breaks the Cargo.toml https://travis-ci.org/BenTheElder/slack-rs/builds/83414830
I have a `[[bin]]` setup so that `cargo run example -- <api_key>` work; that will need updating.

**Comment by mthjones** [comment]
Should the example be getting run by travis or just verifying that it builds successfully?

**Comment by BenTheElder** [comment]
Just built successfully, the example needs to be run with an api key so
when I'm developing I run it locally.

**Comment by mthjones** [comment]
Updated to fix the Travis issue. `cargo test` gets run by Travis by default, and that tries to build all examples. If any fail to build, then Travis too will fail.

**Comment by BenTheElder** [comment]
Thanks!

**Comment by BenTheElder** [comment]
Updated changelog to include, 0.8.3 will reflect this. (pushing those changes momentarily)

**Pull request merged**
