### PR TITLE
Slack web API hyper call refactor

### PR DESCRIPTION
**Pull request by mthjones**
Moved a lot of the repeated logic around calling the Slack web API via Hyper into its own method.

Should make supporting the rest of the API endpoints a bit easier!

*Note*: This also fixes a typo that would cause calling `post_message` with attachments to not include the attachments.

### CODE REVIEW

**Comment by BenTheElder** [comment]
Looks great!

Nit: Not important but, the merge commit from master being merged back to master is kinda messy, could you maybe squash these commits?

**Comment by mthjones** [comment]
Squashed! I also have another PR that replaces a lot of the Result matches with `try!`. Would you prefer I merge that into this one or just open a new one?

**Comment by BenTheElder** [comment]
Thanks!

I think I'd prefer a separate PR for the try! changes.

**Comment by BenTheElder** [comment]
Thanks again, this is a nice net cleanup that needed to happen. ☺

**Pull request merged**
